language: ruby

install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "l7CW/saUOuecD/Ue0hWCTOWR0fdd7avyn6C4zAdRzdKFDVw+1P2DtsrIIeszJPjq7zthyFEDvNkwU7JvOuSW28UUSpWTZ6IZ4SbB5sxrEnulQRGotCQbXOlcAN0pd3G2NJ41yU01zwm/mratQ9kwvt7yVwqdeTtYmne27RQVaCCYOx4xY4cUjgqPwSdVN/Nw8l0fGYxmjEfXlc2/eNHGR1RAVPWVUJ4Rrq2Gou5cJyp4MeVQXr9Hng9oHy0y8FsG7Sk+PEXhmhQK3/YcvLcoFE7VP2pyCQoi90sewsZfJAxVCc+a7DvqYuAHC0IooP65QJaw3PEeYynUhfp18tcLbjtqsFSGYJwo8fHBfsx+w36JWTFu9/cSVCZcMprShzjBNitqq5jIB6Ehe0TjjJSK5OLJKxV14mPRQLZnNXVL2SXQ6bGYUwBRiuO2O33K3KHRvud2/JNXSgYRzHdXyM7tj7WnfwkWTUI0gvqHEvQyFo1cv8OFCCrYGrhQgxyMgpNW6T55LX1oXD0xOiGWM/8Em/XfhlZKjcRj6rNulWoXTYQn3omoqkwYR4zmkTnsN1q6XfRNQUGOQpamBrSzsI2u9SmNsGWLctPiLUIsD7sGOGKR5Hyj5aTPrYwNjS7/J7e038TuKKR4Qn94mTiu616q97OhIFiNyZE6t7VVWBYg2pU="
