# core settings
lang: "ja"
title: HCPC 北海道大学競技プログラミングサークル
header_title: 北大競プロサークル
description: 北海道大学にあります、競技プログラミングの練習会・勉強会を行うサークルです。
show_downloads: true

# build source / destination
source: ./
destination: ./ci-build/

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://hcpc-hokudai.github.io" # change this to the base hostname & protocol for your site
google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
theme: # leave it empty

# social
author: HCPC 北海道大学競技プログラミングサークル
image: /hcpc-thumbnail.png
twitter:
  username: hcpc_hokudai
github:
  owner_name: HCPC
  owner_url: https://github.com/hcpc-hokudai

# for running ci
username: hcpc-hokudai
repo: hcpc-hokudai.github.io
branch: source

# url definitions
header_page_refs: ['about', 'activities', 'contact']

aoj_hupc_url: 'https://onlinejudge.u-aizu.ac.jp/challenges/sources/VPC/HUPC/'
aoj_contest_url: 'https://onlinejudge.u-aizu.ac.jp/services/room.html#'
reg_atnd_url: 'https://atnd.org/events/'
reg_kokucheese_url: 'https://kokucheese.com/event/index/'
hcpc_archive_url: 'https://hcpc-hokudai.github.io/archive/'

# not to build
exclude:
  - script
  - vendor
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - jekyll-theme-cayman-blog.gemspec
  - docs/
  - thumbnail/
  - .gitignore

# safe: false # for using plugins
# pygments: true

# plugins:
#  - jekyll-target-blank

# target-blank:
#     rel: nofollow

jekyll_admin:
    hidden_links:
