name: web-deploy
on:
  push:
    branches:
      - source
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone into ci-build
        uses: actions/checkout@v4
        with:
          path: ci-build
          ref: master
      - name: Setup Ruby 3.4.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true
      - name: Install Packages
        run: |
          gem install bundler -v 2.6.8
          bundle install
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global push.default simple
      - name: Deploy
        run: |
          bundle exec rake site:deploy --quiet
